spring:
  application:
    name: auth-service
  profiles:
    active: local
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}